services:
  doto-postgres:
    image: postgres:16-alpine
    container_name: doto-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: doto
    ports:
      - "5432:5432"
    volumes:
      - doto_pgdata:/var/lib/postgresql/data

volumes:
  doto_pgdata:
